Repository Illusory-Team/work-fly-server, pull requests merged in 2023-04, with the labels that each got.

#19 feature/861mjearr
  .env.example
  prisma/migrations/20230326100807_csrf_tokens/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/user-data.dto.ts
  src/auth/strategies/access-token.strategy.ts
  src/auth/strategies/index.ts
  src/auth/strategies/refresh-token.strategy.ts
  src/common/guards/accessToken.guard.ts
  src/common/guards/csrfAndAccessToken.guard.ts
  src/common/guards/index.ts
  src/tokens/dto/tokens.dto.ts
  src/tokens/tokens.constants.ts
  src/tokens/tokens.service.ts
Labels: feature

#20 refactor/85zrw4qmu
  .prettierrc
  down.sql
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/index.ts
  src/auth/dto/register-user-owner.dto.ts
  src/auth/dto/responses/auth-response.dto.ts
  src/auth/dto/return/set-session-return.dto.ts
  src/auth/dto/return/user-return.dto.ts
  src/auth/dto/user-session.dto.ts
  src/auth/interfaces/access-jwt-payload.interface.ts
  src/auth/interfaces/index.ts
  src/auth/interfaces/refresh-jwt-payload.interface.ts
  src/auth/strategies/access-token.strategy.ts
  src/auth/strategies/index.ts
  src/auth/strategies/refresh-token.strategy.ts
  src/common/constants/error/emailPasswordIncorrect.constant.ts
  src/common/constants/error/index.ts
  src/common/constants/error/noSession.constant.ts
  src/common/constants/error/notFound.constant.ts
  src/common/constants/error/nothingPassed.constant.ts
  src/common/constants/error/unauthorized.constant.ts
  src/common/constants/error/userExists.constant.ts
  src/common/constants/index.ts
  src/common/constants/isPublicKey.constant.ts
  src/common/constants/phoneValidation.constant.ts
  src/common/constants/position.constant.ts
  src/common/constants/swagger/imageValidation.constant.ts
  src/common/constants/swagger/index.ts
  src/common/constants/swagger/phoneValidation.constant.ts
  src/common/constants/swagger/position.constant.ts
  src/common/constants/swagger/validation.constant.ts
  src/common/decorators/is-phone-number.decorator.ts
  src/common/decorators/public.decorator.ts
  src/common/guards/accessToken.guard.ts
  src/common/guards/csrfAndAccessToken.guard.ts
  src/common/guards/csrfAndRefreshToken.guard.ts
  src/common/guards/index.ts
  src/common/guards/refreshToken.guard.ts
  src/companies/companies.controller.ts
  src/companies/companies.service.ts
  src/folders/appearance/folder-appearances.controller.ts
  src/folders/appearance/folder-appearances.service.ts
  src/folders/folders.controller.ts
  src/folders/folders.service.ts
  src/folders/services/folder-types.service.ts
  src/main.ts
  src/positions/positions.service.ts
  src/tokens/dto/tokens.dto.ts
  src/tokens/tokens.service.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/index.ts
  src/users/dto/pure-relations-user.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  tsconfig.json
Labels: documentation, refactoring

#22 [refactor/WF-106]: refactor param options in controller
  package-lock.json
  package.json
  src/common/guards/csrfAndAccessToken.guard.ts
  src/users/users.controller.ts
Labels: refactoring
